version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - directory: "/"
    package-ecosystem: "gradle"
    schedule:
      interval: "daily"
  - directory: "/MixinsTranslator"
    package-ecosystem: "gradle"
    schedule:
      interval: "daily"
  - directory: "/MixinsDummy"
    package-ecosystem: "gradle"
    schedule:
      interval: "daily"
  - directory: "/AdditionalClassProvider"
    package-ecosystem: "gradle"
    schedule:
      interval: "daily"
